### PR TITLE
qrexec-lib/pack: don't use curly quotes in error messages

### LINKED ISSUE #8738: Error message sometimes missing when inter-qube file copy/move fails due to disallowed characters in filename
### Qubes OS release
4.2.0
Installed RC4 and installed updates since then.

### Brief summary
As discussed in #8332 , copy/move files can fail when there are non-english characters, and that is an intended behavior.

However, copy/move sometimes fails _without_ any warning message, which can result in loss of data. 

### Steps to reproduce

Create a file named  عربية or עברית, e.g. `touch عربية` or `touch עברית`.
From the file manager, choose copy to other appVM.

### Expected behavior
File is copied or an error message is presented.

### Actual behavior
File not copied and no error message is displayed to user.

I haven't checked if command line provides any error indication, but if it does not, it would create issues with automatic scripts.

As side note, I am sure that the choice to have strict file name validation has been debated. I personally find that it damages usability (even if there is an error message) because user have existing files and receive files from others. I am sure that there are good security reasons for the choice.

### PR DESCRIPTION
**Pull request by rustybird**
Fixes QubesOS/qubes-issues#8738

### CODE REVIEW

**Comment by DemiMarie** [comment]
@rustybird Why would this fix the bug?

The use of curly quotes is actually intentional here: I believe the reply is limited to ASCII-only, so this prevents spoofing attacks as the quotes will always enclose the _actual_ reply.  However, the reply should be filtered the same way that the file name is, so this is not going to be a valid advantage once that bug is fixed.

**Comment by marmarek** [comment]
> @rustybird Why would this fix the bug?

See commit message - curly quotes are not valid characters in locales that don't enable UTF-8 (for example with `LC_ALL=C`).

**Comment by DemiMarie** [comment]
> > @rustybird Why would this fix the bug?
> 
> See commit message - curly quotes are not valid characters in locales that don't enable UTF-8 (for example with `LC_ALL=C`).

I see :woman_facepalming:.  What about using `LC_ALL=C.UTF-8` instead?

**Comment by marmarek** [comment]
> I see 🤦‍♀️. What about using `LC_ALL=C.UTF-8` instead?

It isn't always supported (AFAIR it isn't standardized yet). And you shouldn't override locale for printing error message that may be translated at some point.

And generally, it was my oversight to even accept this non-ASCII part of the message.

**Pull request merged**
